import Gaffer
import GafferScene
import IECore
import imath
import ofNode.processorNodes

Gaffer.Metadata.registerValue( parent, "serialiser:milestoneVersion", 1, persistent=False )
Gaffer.Metadata.registerValue( parent, "serialiser:majorVersion", 3, persistent=False )
Gaffer.Metadata.registerValue( parent, "serialiser:minorVersion", 3, persistent=False )
Gaffer.Metadata.registerValue( parent, "serialiser:patchVersion", 0, persistent=False )

__children = {}

__children["Reverse_Selection"] = Gaffer.Box( "Reverse_Selection" )
parent.addChild( __children["Reverse_Selection"] )
__children["Reverse_Selection"].addChild( GafferScene.Isolate( "Isolate" ) )
__children["Reverse_Selection"]["Isolate"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( GafferScene.PathFilter( "PathFilter" ) )
__children["Reverse_Selection"]["PathFilter"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( GafferScene.PathFilter( "PathFilter1" ) )
__children["Reverse_Selection"]["PathFilter1"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( GafferScene.Isolate( "Isolate1" ) )
__children["Reverse_Selection"]["Isolate1"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( ofNode.processorNodes.Replace( "Replace" ) )
__children["Reverse_Selection"]["Replace"]["children"].addChild( GafferScene.ScenePlug( "child1", flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"]["Replace"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( GafferScene.SubTree( "SubTree" ) )
__children["Reverse_Selection"]["SubTree"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( Gaffer.BoxIn( "BoxIn" ) )
__children["Reverse_Selection"]["BoxIn"].setup( GafferScene.ScenePlug( "out", ) )
__children["Reverse_Selection"]["BoxIn"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( GafferScene.ScenePlug( "in", flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( Gaffer.BoxOut( "BoxOut" ) )
__children["Reverse_Selection"]["BoxOut"].setup( GafferScene.ScenePlug( "in", ) )
__children["Reverse_Selection"]["BoxOut"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( GafferScene.ScenePlug( "out", direction = Gaffer.Plug.Direction.Out, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( Gaffer.StringVectorDataPlug( "Source_Path", defaultValue = IECore.StringVectorData( [  ] ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( Gaffer.StringVectorDataPlug( "Reverse_Selection_Path", defaultValue = IECore.StringVectorData( [  ] ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( Gaffer.Dot( "Dot" ) )
__children["Reverse_Selection"]["Dot"].setup( GafferScene.FilterPlug( "in", defaultValue = 0, minValue = 0, maxValue = 7, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.AcceptsDependencyCycles, ) )
__children["Reverse_Selection"]["Dot"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( Gaffer.Dot( "Dot1" ) )
__children["Reverse_Selection"]["Dot1"].setup( GafferScene.ScenePlug( "in", ) )
__children["Reverse_Selection"]["Dot1"].addChild( Gaffer.BoolPlug( "__uiInputConnectionsMinimised", defaultValue = False, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"]["Dot1"].addChild( Gaffer.BoolPlug( "__uiOutputConnectionsMinimised", defaultValue = False, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( Gaffer.BoolPlug( "enabled", defaultValue = True, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Reverse_Selection"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"], 'noduleLayout:customGadget:addButtonTop:visible', False )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"], 'noduleLayout:customGadget:addButtonBottom:visible', False )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"], 'noduleLayout:customGadget:addButtonLeft:visible', False )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"], 'noduleLayout:customGadget:addButtonRight:visible', False )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"], 'documentation:url', '' )
__children["Reverse_Selection"]["Isolate"]["in"].setInput( __children["Reverse_Selection"]["BoxIn"]["out"] )
__children["Reverse_Selection"]["Isolate"]["filter"].setInput( __children["Reverse_Selection"]["PathFilter"]["out"] )
__children["Reverse_Selection"]["Isolate"]["__uiPosition"].setValue( imath.V2f( 92.7382431, 38.4001923 ) )
__children["Reverse_Selection"]["PathFilter"]["paths"].setInput( __children["Reverse_Selection"]["Source_Path"] )
__children["Reverse_Selection"]["PathFilter"]["__uiPosition"].setValue( imath.V2f( 111.338234, 42.6117592 ) )
__children["Reverse_Selection"]["PathFilter1"]["paths"].setInput( __children["Reverse_Selection"]["Reverse_Selection_Path"] )
__children["Reverse_Selection"]["PathFilter1"]["__uiPosition"].setValue( imath.V2f( 114.795624, 34.7061462 ) )
__children["Reverse_Selection"]["Isolate1"]["in"].setInput( __children["Reverse_Selection"]["Isolate"]["out"] )
__children["Reverse_Selection"]["Isolate1"]["filter"].setInput( __children["Reverse_Selection"]["PathFilter1"]["out"] )
__children["Reverse_Selection"]["Isolate1"]["__uiPosition"].setValue( imath.V2f( 92.7382431, 30.2361298 ) )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Replace"], 'childNodesAreReadOnly', True )
__children["Reverse_Selection"]["Replace"]["out"].setInput( __children["Reverse_Selection"]["Replace"]["Enabler"]["out"] )
__children["Reverse_Selection"]["Replace"]["in"].setInput( __children["Reverse_Selection"]["BoxIn"]["out"] )
__children["Reverse_Selection"]["Replace"]["filter"].setInput( __children["Reverse_Selection"]["Dot"]["out"] )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Replace"]["children"], 'nodule:type', 'GafferUI::CompoundNodule' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Replace"]["children"], 'plugValueWidget:type', '' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Replace"]["children"], 'noduleLayout:spacing', 0.5 )
__children["Reverse_Selection"]["Replace"]["children"][0].setInput( __children["Reverse_Selection"]["SubTree"]["out"] )
__children["Reverse_Selection"]["Replace"]["__uiPosition"].setValue( imath.V2f( 80.0875244, 10.4157658 ) )
__children["Reverse_Selection"]["SubTree"]["in"].setInput( __children["Reverse_Selection"]["Isolate1"]["out"] )
__children["Reverse_Selection"]["SubTree"]["root"].setInput( __children["Reverse_Selection"]["PathFilter"]["paths"] )
__children["Reverse_Selection"]["SubTree"]["inheritTransform"].setValue( True )
__children["Reverse_Selection"]["SubTree"]["inheritAttributes"].setValue( True )
__children["Reverse_Selection"]["SubTree"]["inheritSetMembership"].setValue( True )
__children["Reverse_Selection"]["SubTree"]["__uiPosition"].setValue( imath.V2f( 92.7382431, 22.3361282 ) )
__children["Reverse_Selection"]["BoxIn"]["__in"].setInput( __children["Reverse_Selection"]["in"] )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["BoxIn"]["__in"], 'nodule:color', imath.Color3f( 0.240099996, 0.339399993, 0.485000014 ) )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["BoxIn"]["__in"], 'nodule:type', 'GafferUI::StandardNodule' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["BoxIn"]["__in"], 'description', 'The input scene' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["BoxIn"]["__in"], 'plugValueWidget:type', '' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["BoxIn"]["__in"], 'noduleLayout:spacing', 2.0 )
__children["Reverse_Selection"]["BoxIn"]["__uiPosition"].setValue( imath.V2f( 77.8375244, 46.7322235 ) )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["in"], 'nodule:color', imath.Color3f( 0.240099996, 0.339399993, 0.485000014 ) )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["in"], 'nodule:type', 'GafferUI::StandardNodule' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["in"], 'description', 'The input scene' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["in"], 'plugValueWidget:type', '' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["in"], 'noduleLayout:spacing', 2.0 )
__children["Reverse_Selection"]["BoxOut"]["in"].setInput( __children["Reverse_Selection"]["Replace"]["out"] )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["BoxOut"]["__out"], 'nodule:color', imath.Color3f( 0.240099996, 0.339399993, 0.485000014 ) )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["BoxOut"]["__out"], 'description', 'The processed output scene.' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["BoxOut"]["__out"], 'nodule:type', 'GafferUI::StandardNodule' )
__children["Reverse_Selection"]["BoxOut"]["passThrough"].setInput( __children["Reverse_Selection"]["Dot1"]["out"] )
__children["Reverse_Selection"]["BoxOut"]["enabled"].setInput( __children["Reverse_Selection"]["enabled"] )
__children["Reverse_Selection"]["BoxOut"]["__uiPosition"].setValue( imath.V2f( 81.5875244, 2.08373451 ) )
__children["Reverse_Selection"]["out"].setInput( __children["Reverse_Selection"]["BoxOut"]["__out"] )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["out"], 'nodule:color', imath.Color3f( 0.240099996, 0.339399993, 0.485000014 ) )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["out"], 'description', 'The processed output scene.' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["out"], 'nodule:type', 'GafferUI::StandardNodule' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Source_Path"], 'description', "The list of paths to the locations to be matched by the filter.\nA path is formed by a sequence of names separated by `/`, and\nspecifies the hierarchical position of a location within the scene.\nPaths may use Gaffer's standard wildcard characters to match\nmultiple locations.\n\nThe `*` wildcard matches any sequence of characters within\nan individual name, but never matches across names separated\nby a `/`.\n\n - `/robot/*Arm` matches `/robot/leftArm`, `/robot/rightArm` and\n   `/robot/Arm`. But does not match `/robot/limbs/leftArm` or\n   `/robot/arm`.\n\nThe `...` wildcard matches any sequence of names, and can be\nused to match locations no matter where they are parented in\nthe hierarchy.\n\n - `/.../house` matches `/house`, `/street/house` and `/city/street/house`." )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Source_Path"], 'nodule:type', '' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Source_Path"], 'ui:scene:acceptsPaths', True )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Source_Path"], 'vectorDataPlugValueWidget:dragPointer', 'objects' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Source_Path"], 'plugValueWidget:type', 'GafferSceneUI.PathFilterUI._PathsPlugValueWidget' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Reverse_Selection_Path"], 'description', "The list of paths to the locations to be matched by the filter.\nA path is formed by a sequence of names separated by `/`, and\nspecifies the hierarchical position of a location within the scene.\nPaths may use Gaffer's standard wildcard characters to match\nmultiple locations.\n\nThe `*` wildcard matches any sequence of characters within\nan individual name, but never matches across names separated\nby a `/`.\n\n - `/robot/*Arm` matches `/robot/leftArm`, `/robot/rightArm` and\n   `/robot/Arm`. But does not match `/robot/limbs/leftArm` or\n   `/robot/arm`.\n\nThe `...` wildcard matches any sequence of names, and can be\nused to match locations no matter where they are parented in\nthe hierarchy.\n\n - `/.../house` matches `/house`, `/street/house` and `/city/street/house`." )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Reverse_Selection_Path"], 'nodule:type', '' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Reverse_Selection_Path"], 'ui:scene:acceptsPaths', True )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Reverse_Selection_Path"], 'vectorDataPlugValueWidget:dragPointer', 'objects' )
Gaffer.Metadata.registerValue( __children["Reverse_Selection"]["Reverse_Selection_Path"], 'plugValueWidget:type', 'GafferSceneUI.PathFilterUI._PathsPlugValueWidget' )
__children["Reverse_Selection"]["Dot"]["in"].setInput( __children["Reverse_Selection"]["PathFilter"]["out"] )
__children["Reverse_Selection"]["Dot"]["__uiPosition"].setValue( imath.V2f( 111.338234, 14.2460928 ) )
__children["Reverse_Selection"]["Dot1"]["in"].setInput( __children["Reverse_Selection"]["BoxIn"]["out"] )
__children["Reverse_Selection"]["Dot1"]["__uiInputConnectionsMinimised"].setValue( True )
__children["Reverse_Selection"]["__uiPosition"].setValue( imath.V2f( -24.1528015, -86.7033691 ) )


del __children

