###
#This is an experimental node that is quickly implemented
#in the project and has a certain complexity. 
#There is a PythonCommand in the node that needs to be 
#executed in Gaffer's PythonEditor.
###

import Gaffer
import GafferDispatch
import GafferScene
import IECore
import imath

Gaffer.Metadata.registerValue( parent, "serialiser:milestoneVersion", 1, persistent=False )
Gaffer.Metadata.registerValue( parent, "serialiser:majorVersion", 3, persistent=False )
Gaffer.Metadata.registerValue( parent, "serialiser:minorVersion", 3, persistent=False )
Gaffer.Metadata.registerValue( parent, "serialiser:patchVersion", 0, persistent=False )

__children = {}

__children["Crowds_BoundCenter"] = Gaffer.Box( "Crowds_BoundCenter" )
parent.addChild( __children["Crowds_BoundCenter"] )
__children["Crowds_BoundCenter"].addChild( GafferScene.Isolate( "Isolate" ) )
__children["Crowds_BoundCenter"]["Isolate"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferScene.ScenePlug( "in", flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferScene.PathFilter( "PathFilter" ) )
__children["Crowds_BoundCenter"]["PathFilter"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferScene.BoundQuery( "BoundQuery" ) )
__children["Crowds_BoundCenter"]["BoundQuery"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferScene.Transform( "Transform" ) )
__children["Crowds_BoundCenter"]["Transform"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferScene.Sphere( "Sphere" ) )
__children["Crowds_BoundCenter"]["Sphere"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferScene.PathFilter( "PathFilter1" ) )
__children["Crowds_BoundCenter"]["PathFilter1"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferScene.MergeScenes( "MergeScenes" ) )
__children["Crowds_BoundCenter"]["MergeScenes"]["in"].addChild( GafferScene.ScenePlug( "in2", flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"]["MergeScenes"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferScene.ScenePlug( "out", direction = Gaffer.Plug.Direction.Out, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( Gaffer.Spreadsheet( "Spreadsheet" ) )
__children["Crowds_BoundCenter"]["Spreadsheet"]["rows"].addColumn( Gaffer.StringPlug( "location", defaultValue = '', ) )
__children["Crowds_BoundCenter"]["Spreadsheet"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferScene.CollectScenes( "CollectScenes" ) )
__children["Crowds_BoundCenter"]["CollectScenes"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferScene.FilterResults( "FilterResults" ) )
__children["Crowds_BoundCenter"]["FilterResults"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferScene.PathFilter( "PathFilter4" ) )
__children["Crowds_BoundCenter"]["PathFilter4"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( GafferDispatch.PythonCommand( "PythonCommand" ) )
__children["Crowds_BoundCenter"]["PythonCommand"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( Gaffer.Dot( "Dot" ) )
__children["Crowds_BoundCenter"]["Dot"].setup( GafferScene.ScenePlug( "in", ) )
__children["Crowds_BoundCenter"]["Dot"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( Gaffer.Dot( "Dot5" ) )
__children["Crowds_BoundCenter"]["Dot5"].setup( GafferScene.ScenePlug( "in", ) )
__children["Crowds_BoundCenter"]["Dot5"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( Gaffer.Dot( "Dot6" ) )
__children["Crowds_BoundCenter"]["Dot6"].setup( GafferScene.ScenePlug( "in", ) )
__children["Crowds_BoundCenter"]["Dot6"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( Gaffer.BoxIn( "BoxIn" ) )
__children["Crowds_BoundCenter"]["BoxIn"].setup( GafferScene.ScenePlug( "out", ) )
__children["Crowds_BoundCenter"]["BoxIn"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( Gaffer.BoxOut( "BoxOut" ) )
__children["Crowds_BoundCenter"]["BoxOut"].setup( GafferScene.ScenePlug( "in", ) )
__children["Crowds_BoundCenter"]["BoxOut"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( Gaffer.StringVectorDataPlug( "paths", defaultValue = IECore.StringVectorData( [  ] ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( Gaffer.Dot( "Dot7" ) )
__children["Crowds_BoundCenter"]["Dot7"].setup( GafferScene.ScenePlug( "in", ) )
__children["Crowds_BoundCenter"]["Dot7"].addChild( Gaffer.BoolPlug( "__uiInputConnectionsMinimised", defaultValue = False, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"]["Dot7"].addChild( Gaffer.BoolPlug( "__uiOutputConnectionsMinimised", defaultValue = False, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"]["Dot7"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( Gaffer.BoolPlug( "enabled", defaultValue = True, flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
__children["Crowds_BoundCenter"].addChild( Gaffer.V2fPlug( "__uiPosition", defaultValue = imath.V2f( 0, 0 ), flags = Gaffer.Plug.Flags.Default | Gaffer.Plug.Flags.Dynamic, ) )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"], 'documentation:url', '' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"], 'noduleLayout:customGadget:addButtonTop:visible', False )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"], 'noduleLayout:customGadget:addButtonBottom:visible', False )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"], 'noduleLayout:customGadget:addButtonLeft:visible', False )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"], 'noduleLayout:customGadget:addButtonRight:visible', False )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"], 'icon', 'boxNode.png' )
__children["Crowds_BoundCenter"]["Isolate"]["in"].setInput( __children["Crowds_BoundCenter"]["BoxIn"]["out"] )
__children["Crowds_BoundCenter"]["Isolate"]["filter"].setInput( __children["Crowds_BoundCenter"]["PathFilter"]["out"] )
__children["Crowds_BoundCenter"]["Isolate"]["__uiPosition"].setValue( imath.V2f( 53.5625458, 41.6381149 ) )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["in"], 'nodule:color', imath.Color3f( 0.240099996, 0.339399993, 0.485000014 ) )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["in"], 'nodule:type', 'GafferUI::StandardNodule' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["in"], 'description', 'The input scene' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["in"], 'plugValueWidget:type', '' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["in"], 'noduleLayout:spacing', 2.0 )
__children["Crowds_BoundCenter"]["PathFilter"]["paths"].setInput( __children["Crowds_BoundCenter"]["paths"] )
__children["Crowds_BoundCenter"]["PathFilter"]["__uiPosition"].setValue( imath.V2f( 66.0805664, 47.6224289 ) )
__children["Crowds_BoundCenter"]["BoundQuery"]["scene"].setInput( __children["Crowds_BoundCenter"]["Dot5"]["out"] )
__children["Crowds_BoundCenter"]["BoundQuery"]["location"].setInput( __children["Crowds_BoundCenter"]["Spreadsheet"]["out"]["location"] )
__children["Crowds_BoundCenter"]["BoundQuery"]["__uiPosition"].setValue( imath.V2f( 53.5625458, 26.6502934 ) )
__children["Crowds_BoundCenter"]["Transform"]["in"].setInput( __children["Crowds_BoundCenter"]["Sphere"]["out"] )
__children["Crowds_BoundCenter"]["Transform"]["filter"].setInput( __children["Crowds_BoundCenter"]["PathFilter1"]["out"] )
__children["Crowds_BoundCenter"]["Transform"]["transform"]["translate"].setInput( __children["Crowds_BoundCenter"]["BoundQuery"]["center"] )
__children["Crowds_BoundCenter"]["Transform"]["__uiPosition"].setValue( imath.V2f( 85.5959167, 22.8179436 ) )
__children["Crowds_BoundCenter"]["Sphere"]["__uiPosition"].setValue( imath.V2f( 85.5959167, 40.7728539 ) )
__children["Crowds_BoundCenter"]["PathFilter1"]["paths"].setInput( __children["Crowds_BoundCenter"]["Spreadsheet"]["enabledRowNames"] )
__children["Crowds_BoundCenter"]["PathFilter1"]["__uiPosition"].setValue( imath.V2f( 99.9497681, 28.6953545 ) )
__children["Crowds_BoundCenter"]["MergeScenes"]["in"][0].setInput( __children["Crowds_BoundCenter"]["Dot6"]["out"] )
__children["Crowds_BoundCenter"]["MergeScenes"]["in"][1].setInput( __children["Crowds_BoundCenter"]["CollectScenes"]["out"] )
__children["Crowds_BoundCenter"]["MergeScenes"]["__uiPosition"].setValue( imath.V2f( 62.9659958, 0.717743278 ) )
__children["Crowds_BoundCenter"]["out"].setInput( __children["Crowds_BoundCenter"]["BoxOut"]["__out"] )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["out"], 'nodule:color', imath.Color3f( 0.240099996, 0.339399993, 0.485000014 ) )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["out"], 'description', 'The processed output scene.' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["out"], 'nodule:type', 'GafferUI::StandardNodule' )
__children["Crowds_BoundCenter"]["Spreadsheet"]["selector"].setValue( '${collect:rootName}' )
__children["Crowds_BoundCenter"]["Spreadsheet"]["rows"][0]["cells"]["location"]["value"].setValue( '/crowds/S9010_0020_crowds/Mdggrp_1/anim' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["Spreadsheet"]["rows"][0]["cells"]["location"], 'spreadsheet:columnWidth', 309 )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["Spreadsheet"]["rows"][0]["cells"]["location"]["value"], 'ui:scene:acceptsSetName:promotable', False )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["Spreadsheet"]["rows"][0]["cells"]["location"]["value"], 'ui:scene:acceptsSetNames:promotable', False )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["Spreadsheet"]["rows"][0]["cells"]["location"]["value"], 'ui:scene:acceptsSetExpression:promotable', False )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["Spreadsheet"]["rows"][0]["cells"]["location"]["value"], 'description', 'The location within the scene to query the bound at.\n> Note : If the location does not exist then the query will not be\n> performed and all outputs will be set to their default values.' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["Spreadsheet"]["rows"][0]["cells"]["location"]["value"], 'plugValueWidget:type', 'GafferSceneUI.ScenePathPlugValueWidget' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["Spreadsheet"]["rows"][0]["cells"]["location"]["value"], 'scenePathPlugValueWidget:scene', 'scene' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["Spreadsheet"]["rows"][0]["cells"]["location"]["value"], 'nodule:type', '' )
__children["Crowds_BoundCenter"]["Spreadsheet"]["__uiPosition"].setValue( imath.V2f( 75.6302185, 26.4259281 ) )
__children["Crowds_BoundCenter"]["CollectScenes"]["in"].setInput( __children["Crowds_BoundCenter"]["Transform"]["out"] )
__children["Crowds_BoundCenter"]["CollectScenes"]["rootNames"].setInput( __children["Crowds_BoundCenter"]["Spreadsheet"]["enabledRowNames"] )
__children["Crowds_BoundCenter"]["CollectScenes"]["sourceRoot"].setValue( '/${collect:rootName}' )
__children["Crowds_BoundCenter"]["CollectScenes"]["__uiPosition"].setValue( imath.V2f( 85.5959167, 8.88180637 ) )
__children["Crowds_BoundCenter"]["FilterResults"]["scene"].setInput( __children["Crowds_BoundCenter"]["Dot5"]["out"] )
__children["Crowds_BoundCenter"]["FilterResults"]["filter"].setInput( __children["Crowds_BoundCenter"]["PathFilter4"]["out"] )
__children["Crowds_BoundCenter"]["FilterResults"]["root"].setInput( __children["Crowds_BoundCenter"]["PathFilter"]["paths"] )
__children["Crowds_BoundCenter"]["FilterResults"]["__uiPosition"].setValue( imath.V2f( 65.2176056, 26.9740524 ) )
__children["Crowds_BoundCenter"]["PathFilter4"]["paths"].setValue( IECore.StringVectorData( [ '.../anim' ] ) )
__children["Crowds_BoundCenter"]["PathFilter4"]["__uiPosition"].setValue( imath.V2f( 72.7151794, 41.6381149 ) )
__children["Crowds_BoundCenter"]["PythonCommand"]["command"].setValue( '#获取crow组的所有anim\ndata_list = root[\'FilterResults\'][\'outStrings\'].getValue()\n#将所有群组数据添加到列表里\ndata_list1 = []\nfor i in data_list:\n\tdata_list1.append(i)\n#计算群组数量\ndata_list_len = len(data_list1)\n#计算需要多少个sphere去替代并转为列表\ncount=[]\nfor i in range(1,data_list_len+1):\n\tcount.append(i)\n\n#将小球数量和Bound中心位置添加到表格完成创建\nfor i,s in zip(count,data_list1):\n\troot["Spreadsheet"]["rows"].addRow()\n\ti = str(i)\n\trow = "row"+i\n\troot["Spreadsheet"]["rows"][row]["name"].setValue(i)\n\troot["Spreadsheet"]["rows"][row]["cells"]["location"]["value"].setValue(s)' )
__children["Crowds_BoundCenter"]["PythonCommand"]["__uiPosition"].setValue( imath.V2f( 104.240822, 15.4636621 ) )
__children["Crowds_BoundCenter"]["Dot"]["in"].setInput( __children["Crowds_BoundCenter"]["Dot5"]["out"] )
__children["Crowds_BoundCenter"]["Dot"]["__uiPosition"].setValue( imath.V2f( 38.9770012, 27.8060837 ) )
__children["Crowds_BoundCenter"]["Dot5"]["in"].setInput( __children["Crowds_BoundCenter"]["Isolate"]["out"] )
__children["Crowds_BoundCenter"]["Dot5"]["__uiPosition"].setValue( imath.V2f( 53.5625458, 34.3060837 ) )
__children["Crowds_BoundCenter"]["Dot6"]["in"].setInput( __children["Crowds_BoundCenter"]["Dot"]["out"] )
__children["Crowds_BoundCenter"]["Dot6"]["__uiPosition"].setValue( imath.V2f( 38.9770012, 8.04977417 ) )
__children["Crowds_BoundCenter"]["BoxIn"]["__in"].setInput( __children["Crowds_BoundCenter"]["in"] )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxIn"]["__in"], 'nodule:color', imath.Color3f( 0.240099996, 0.339399993, 0.485000014 ) )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxIn"]["__in"], 'deletable', True )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxIn"]["__in"], 'renameable', True )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxIn"]["__in"], 'nodule:type', 'GafferUI::StandardNodule' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxIn"]["__in"], 'description', 'The input scene' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxIn"]["__in"], 'plugValueWidget:type', '' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxIn"]["__in"], 'noduleLayout:spacing', 2.0 )
__children["Crowds_BoundCenter"]["BoxIn"]["__uiPosition"].setValue( imath.V2f( 53.563324, 49.9701462 ) )
__children["Crowds_BoundCenter"]["BoxOut"]["in"].setInput( __children["Crowds_BoundCenter"]["MergeScenes"]["out"] )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxOut"]["__out"], 'nodule:color', imath.Color3f( 0.240099996, 0.339399993, 0.485000014 ) )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxOut"]["__out"], 'deletable', True )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxOut"]["__out"], 'renameable', True )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxOut"]["__out"], 'description', 'The processed output scene.' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["BoxOut"]["__out"], 'nodule:type', 'GafferUI::StandardNodule' )
__children["Crowds_BoundCenter"]["BoxOut"]["passThrough"].setInput( __children["Crowds_BoundCenter"]["Dot7"]["out"] )
__children["Crowds_BoundCenter"]["BoxOut"]["enabled"].setInput( __children["Crowds_BoundCenter"]["enabled"] )
__children["Crowds_BoundCenter"]["BoxOut"]["__uiPosition"].setValue( imath.V2f( 64.46521, -7.61428833 ) )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["paths"], 'description', "The list of paths to the locations to be matched by the filter.\nA path is formed by a sequence of names separated by `/`, and\nspecifies the hierarchical position of a location within the scene.\nPaths may use Gaffer's standard wildcard characters to match\nmultiple locations.\n\nThe `*` wildcard matches any sequence of characters within\nan individual name, but never matches across names separated\nby a `/`.\n\n - `/robot/*Arm` matches `/robot/leftArm`, `/robot/rightArm` and\n   `/robot/Arm`. But does not match `/robot/limbs/leftArm` or\n   `/robot/arm`.\n\nThe `...` wildcard matches any sequence of names, and can be\nused to match locations no matter where they are parented in\nthe hierarchy.\n\n - `/.../house` matches `/house`, `/street/house` and `/city/street/house`." )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["paths"], 'nodule:type', '' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["paths"], 'ui:scene:acceptsPaths', True )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["paths"], 'vectorDataPlugValueWidget:dragPointer', 'objects' )
Gaffer.Metadata.registerValue( __children["Crowds_BoundCenter"]["paths"], 'plugValueWidget:type', 'GafferSceneUI.PathFilterUI._PathsPlugValueWidget' )
__children["Crowds_BoundCenter"]["Dot7"]["in"].setInput( __children["Crowds_BoundCenter"]["BoxIn"]["out"] )
__children["Crowds_BoundCenter"]["Dot7"]["__uiInputConnectionsMinimised"].setValue( True )
__children["Crowds_BoundCenter"]["Dot7"]["__uiPosition"].setValue( imath.V2f( 71.7159958, -0.113659978 ) )
__children["Crowds_BoundCenter"]["__uiPosition"].setValue( imath.V2f( -33.1830521, -47.6023598 ) )


del __children

